
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightASIGNACIONrightARITMETICArightBOOLMENMAYrightBOOLMENMAYEQUALSrightBOOLDIFrightFORMULASrightSTRINGrightESTRUCTURAARITMETICA ASIGNACION BOOLDIF BOOLMENMAY BOOLMENMAYEQUALS ESTRUCTURA FORMULAS STRINGdeclaracion : ASIGNACIONdeclaracion : ARITMETICAdeclaracion : BOOLMENMAYdeclaracion : BOOLMENMAYEQUALSdeclaracion : BOOLDIFdeclaracion : FORMULASdeclaracion : STRINGdeclaracion : ESTRUCTURA'
    
_lr_action_items = {'ASIGNACION':([0,],[2,]),'ARITMETICA':([0,],[3,]),'BOOLMENMAY':([0,],[4,]),'BOOLMENMAYEQUALS':([0,],[5,]),'BOOLDIF':([0,],[6,]),'FORMULAS':([0,],[7,]),'STRING':([0,],[8,]),'ESTRUCTURA':([0,],[9,]),'$end':([1,2,3,4,5,6,7,8,9,],[0,-1,-2,-3,-4,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaracion':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaracion","S'",1,None,None,None),
  ('declaracion -> ASIGNACION','declaracion',1,'p_declaracion_asignacion','AnalizadorSintactico.py',22),
  ('declaracion -> ARITMETICA','declaracion',1,'p_declaracion_aritmetica','AnalizadorSintactico.py',26),
  ('declaracion -> BOOLMENMAY','declaracion',1,'p_declaracion_boolmenmay','AnalizadorSintactico.py',30),
  ('declaracion -> BOOLMENMAYEQUALS','declaracion',1,'p_declaracion_boolmenmayequals','AnalizadorSintactico.py',34),
  ('declaracion -> BOOLDIF','declaracion',1,'p_declaracion_booldif','AnalizadorSintactico.py',38),
  ('declaracion -> FORMULAS','declaracion',1,'p_declaracion_formulas','AnalizadorSintactico.py',42),
  ('declaracion -> STRING','declaracion',1,'p_declaracion_string','AnalizadorSintactico.py',46),
  ('declaracion -> ESTRUCTURA','declaracion',1,'p_declaracion_estructura','AnalizadorSintactico.py',50),
]
